import { StringKeyObject } from '../types/custom';

const DEFAULT_CURRENCY = 'SGD';
const MANABU_ADMIN_ID = '60538825a36b9c57a8b19978';
const MANABU_ADMIN_PKG_ID = '605388cca36b9c57a8b1997a';
const PAYMENT_GATEWAY_RATE: StringKeyObject = {
  PAYPAL: 0.03,
  STRIPE: 0.01,
  PAYNOW: 0.01,
};
const MANABU_PROCESSING_RATE: StringKeyObject = {
  UNLICENSED: {
    amount: 15,
    currency: DEFAULT_CURRENCY,
    type: 'absolute',
  },
  LICENSED: {
    amount: 0.16,
    type: 'percent',
  },
};
const NODE_ENV = process.env.NODE_ENV!;
const IS_PRODUCTION = NODE_ENV == 'production';
const G_CLIENTID = process.env.G_CLIENTID!;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET!;
const JWT_SECRET = process.env.JWT_SECRET!;
const MANABU_EMAIL_NOREPLY_PASS = process.env.MANABU_EMAIL_NOREPLY_PASS!;
const MANABU_EMAIL_SUPPORT_PASS = process.env.MANABU_EMAIL_SUPPORT_PASS!;
const MONGO_HOST = process.env.MONGO_HOST!;
const MONGO_PASS = process.env.MONGO_PASS!;
const OPEN_EXCHANGE_RATE_API_KEY = process.env.OPEN_EXCHANGE_RATE_API_KEY!;
const PAYPAL_CLIENT_ID = process.env.PAYPAL_CLIENT_ID!;
const PAYPAL_CLIENT_SECRET = process.env.PAYPAL_CLIENT_SECRET!;
const STRIPE_PUBLISHABLE_KEY = process.env.STRIPE_PUBLISHABLE_KEY!;
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY!;
const REDIS_HOST = process.env.REDIS_HOST!;
const REDIS_PASS = process.env.REDIS_PASS!;
const REDIS_PORT = process.env.REDIS_PORT!;
const STRIPE_WEBHOOK_SECREY_KEY = process.env.STRIPE_WEBHOOK_SECREY_KEY!;

// DEV
const OPEN_EXCHANGE_RATE_API_KEY_DEV = process.env.OPEN_EXCHANGE_RATE_API_KEY_DEV!;
const PAYPAL_CLIENT_ID_DEV = process.env.PAYPAL_CLIENT_ID_DEV!;
const PAYPAL_CLIENT_SECRET_DEV = process.env.PAYPAL_CLIENT_SECRET_DEV!;
const STRIPE_PUBLISHABLE_KEY_DEV = process.env.STRIPE_PUBLISHABLE_KEY_DEV!;
const STRIPE_SECRET_KEY_DEV = process.env.STRIPE_SECRET_KEY_DEV!;
const PAYNOW_PUBLIC_KEY_DEV = process.env.PAYNOW_PUBLIC_KEY_DEV!;
const PAYNOW_SECRET_KEY_DEV = process.env.PAYNOW_SECRET_KEY_DEV!;
const STRIPE_WEBHOOK_SECREY_KEY_DEV = process.env.STRIPE_WEBHOOK_SECREY_KEY_DEV!;

export {
  DEFAULT_CURRENCY,
  IS_PRODUCTION,
  MANABU_ADMIN_ID,
  MANABU_ADMIN_PKG_ID,
  MANABU_PROCESSING_RATE,
  G_CLIENTID,
  GOOGLE_CLIENT_SECRET,
  JWT_SECRET,
  MANABU_EMAIL_NOREPLY_PASS,
  MANABU_EMAIL_SUPPORT_PASS,
  MONGO_HOST,
  MONGO_PASS,
  OPEN_EXCHANGE_RATE_API_KEY,
  PAYPAL_CLIENT_ID,
  PAYPAL_CLIENT_SECRET,
  STRIPE_PUBLISHABLE_KEY,
  STRIPE_SECRET_KEY,
  REDIS_HOST,
  REDIS_PASS,
  REDIS_PORT,
  NODE_ENV,
  PAYMENT_GATEWAY_RATE,
  STRIPE_WEBHOOK_SECREY_KEY,
  OPEN_EXCHANGE_RATE_API_KEY_DEV,
  PAYPAL_CLIENT_ID_DEV,
  PAYPAL_CLIENT_SECRET_DEV,
  STRIPE_PUBLISHABLE_KEY_DEV,
  STRIPE_SECRET_KEY_DEV,
  PAYNOW_PUBLIC_KEY_DEV,
  PAYNOW_SECRET_KEY_DEV,
  STRIPE_WEBHOOK_SECREY_KEY_DEV,
};
